# Generated by Django 5.0.3 on 2024-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='video',
        ),
        migrations.AddField(
            model_name='level',
            name='levelTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='pictureSection',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='image'),
        ),
    ]
