# Generated by Django 4.1.2 on 2024-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_level_leveldescription_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='newsImage/', verbose_name='image'),
        ),
    ]
