# Generated by Django 5.0.3 on 2024-03-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_news_newsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='course',
        ),
    ]
