# Generated by Django 5.0.3 on 2024-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_section_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
