# Generated by Django 5.0.3 on 2024-03-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_news_created_at_news_update_at_section_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='level',
            name='image_level',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Image Level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='level',
            name='levelDescription',
            field=models.TextField(verbose_name='Level Description'),
        ),
        migrations.AlterField(
            model_name='level',
            name='levelTitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Level Title'),
        ),
        migrations.AlterField(
            model_name='level',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='news',
            name='lessonsNum',
            field=models.IntegerField(verbose_name='Lesson Number'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='newsImage/', verbose_name='News Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_desc',
            field=models.TextField(verbose_name='News Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=100, verbose_name='News Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='pictureSection',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Image Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectiontitle',
            field=models.CharField(max_length=1000, verbose_name='Section Title'),
        ),
    ]
