# Generated by Django 5.0.3 on 2024-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_news_options_level_image_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='course_name_en',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='levelDescription',
            new_name='level_description_en',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='levelTitle',
            new_name='level_title_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_desc',
            new_name='news_desc_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='news_title_en',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='sectiontitle',
            new_name='section_title_en',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم الكورس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='level_description_ar',
            field=models.TextField(default=1, verbose_name='وصف المستوي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='level_title_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان المستوي'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_desc_ar',
            field=models.TextField(default=1, verbose_name='وصف الخبر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_title_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='عنوان الخبر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='description_ar',
            field=models.TextField(default=1, verbose_name='وصف القسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_title_ar',
            field=models.CharField(default=1, max_length=1000, verbose_name='اسم القسم'),
            preserve_default=False,
        ),
    ]
