# Generated by Django 5.0.3 on 2024-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_coursename_course_course_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Num', models.CharField(max_length=40, verbose_name='phone number')),
                ('Email_url', models.URLField(blank=True, null=True)),
                ('Facebook_url', models.URLField(blank=True, null=True)),
                ('Instgram_url', models.URLField(blank=True, null=True)),
                ('X_url', models.URLField(blank=True, null=True)),
                ('TikTok_url', models.URLField(blank=True, null=True)),
                ('Telgram_url', models.URLField(blank=True, null=True)),
                ('WhatsUp_url', models.URLField(blank=True, null=True)),
                ('LinkeIN_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='level',
            name='image_level',
        ),
    ]
