# Generated by Django 5.0.3 on 2024-03-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_contact_inf_remove_level_image_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_inf',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
    ]
