# Generated by Django 5.0.3 on 2024-03-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_contact_inf_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('-created_at', '-update_at')},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at', '-update_at'), 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('-created_at', '-update_at')},
        ),
        migrations.AddField(
            model_name='contact_inf',
            name='Youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
