# Generated by Django 5.0.3 on 2024-03-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_level_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_inf',
            name='Youtube_url',
        ),
    ]
