# Generated by Django 5.0.3 on 2024-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_contact_inf_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_inf',
            name='Youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
