# Generated by Django 5.0.3 on 2024-03-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_contact_inf_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_inf',
            name='Email_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='Facebook_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='Instgram_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='LinkeIN_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='Telgram_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='TikTok_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='WhatsUp_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='X_url',
        ),
        migrations.RemoveField(
            model_name='contact_inf',
            name='Youtube_url',
        ),
    ]
