# Generated by Django 5.0.3 on 2024-03-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_contact_inf_email_url_contact_inf_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
