# Generated by Django 5.0.3 on 2024-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
