# Generated by Django 5.0.3 on 2024-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_services_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(error_messages={'invalid': 'Invalid value for %(field_name)s.', 'required': '%(field_name)s is required.', 'upload_to': 'Failed to upload file for %(field_name)s.'}, max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='pictureSection',
            field=models.ImageField(default='', upload_to='pictures/', verbose_name='Image Section'),
        ),
    ]
