# Generated by Django 5.0.3 on 2024-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_course_course_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(error_messages={'required': 'Please select a course for this section.'}, max_length=100, verbose_name='Course Name'),
        ),
    ]
