# Generated by Django 5.0.3 on 2024-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_course_course_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(error_messages='ssjjs', max_length=100, verbose_name='Course Name'),
        ),
    ]
