# Generated by Django 5.0.3 on 2024-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_course_course_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='level',
            name='video',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(default='', upload_to='newsImage/', verbose_name='News Image'),
        ),
    ]
