# Generated by Django 5.0.3 on 2024-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_course_course_name_en_alter_level_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='section',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='level',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
